# Generated by Django 4.0.1 on 2022-01-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactform_delete_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='fieldo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
