# Generated by Django 4.0.1 on 2022-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactform_fieldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
